tasks:
  ecoli_rich_medium:
    genes_csv: "data/251117_genomescale_CRISPRi/gene_names.csv"
    model_type: "ecoli_rich_medium"
    transcriptomic_adata:
      path: "data/251117_genomescale_CRISPRi/sample_mix_umi200_hvg500_pc25_neighbors10_mindist0.55.scvi.h5ad"
      perturbation_key: "gene"
      cp10k_layer: "cp10k"
      # raw_layer: "counts" # Optional, used to compute cp10k_layer if not present

methods:
  - method: "gene_graph"
    config_id: "beta_auto"
    params: { "beta": None }
  - method: "gene_graph"
    config_id: "beta_1"
    params: { "beta": 1.0 }
  - method: "fba_moma"
    config_id: "default"
    params: {}
  - method: "fba_gene_graph"
    config_id: "beta_auto"
    params: { "beta": None }
  - method: "fba_gene_graph"
    config_id: "beta_1"
    params: { "beta": 1.0 }
  - method: "llm_embedding"
    config_id: "default"
    params: { "model_name": "embeddinggemma" }

llm_evaluation:
  top_k_pairs: 100
  transcriptomic_tau: 0.1
